name: Update Essay List

# このワークフローは、RSSフィードから最新のエッセイを取得し、
# 指定したMDXファイルにエッセイのタイトルとリンクを追記します。
# 定期実行はcronスケジュールと手動実行の両方で可能です。

on:
  schedule:
    - cron: '*/30 * * * *'  # 30分ごとに実行
  workflow_dispatch:  # 手動実行を可能にする

env:
  MDX_FILE: src/pages/essays.mdx   # 更新対象のMDXファイル
  RSS_URL: https://sizu.me/radish2951/rss   # RSSフィードのURL

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # リポジトリのチェックアウト

      - name: RSSから最新エッセイを取得してMDX更新
        run: |
          # RSSフィードの内容を取得
          rss=$(curl -s "$RSS_URL")
          # 最初の <item> ブロックを抽出
          item=$(echo "$rss" | awk '/<item>/{flag=1} flag; /<\/item>/{flag=0; exit}')
          # <title>タグ内のCDATAセクションからタイトルを抽出
          title=$(echo "$item" | grep -oP '<title>\s*<!\[CDATA\[\K.*?(?=\]\]>)')
          # <link>タグからリンクを抽出
          link=$(echo "$item" | grep -oP '(?<=<link>).*?(?=</link>)')
          
          # MDXファイルにすでに同じリンクがない場合、指定マーカーの直後に追記
          if ! grep -q "${link}" "$MDX_FILE"; then
            sed -i "/NEW_ESSAY_INSERTION_MARKER/ s|$|\n\n[${title}](${link})|" "$MDX_FILE"
          fi

      - name: コミットとプッシュ
        run: |
          # GitHub Actions用のGit設定
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          git add "$MDX_FILE"
          git commit -m "エッセィ追加: ${title}" || true
          git push
