name: Update Essay List

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時（UTC）に実行
  workflow_dispatch:    # 手動実行も可能

env:
  MDX_FILE: src/pages/essays.mdx  # MDXファイルのパスをここに設定

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Install xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: RSSフィードから最新のエッセイを取得
        run: |
          curl -s "https://sizu.me/radish2951/rss" | \
            xmlstarlet sel -t -m "//item[1]" -v "title" -o "|" -v "link" -n > latest_essay.txt
          echo "最新のエッセイ: $(cat latest_essay.txt)"

      - name: MDXファイルの更新
        run: |
          IFS='|' read -r title link < latest_essay.txt
          # 既に同じリンクが存在する場合はスキップ
          if grep -q "${link}" "$MDX_FILE"; then
            echo "既に最新エッセイは登録済みです。"
          else
            # 見出しの直後にエントリを追加（改行を含む）
            sed -i "/## その他いろいろ（しずかなインターネット）/a\\
            \\
            [${title}](${link})" "$MDX_FILE"
          fi

      - name: 変更のコミットとプッシュ
        run: |
          IFS='|' read -r title link < latest_essay.txt
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add "$MDX_FILE"
          git commit -m "エッセィ追加: ${title}" || echo "No changes to commit"
          git push
